{% set name = "Mako" %}
{% set version = "1.1.4" %}
{% set checksum = "17831f0b7087c313c0ffae2bcbbd3c1d5ba9eeac9c38f2eb7b50e8c99fe9d5ab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  preserve_egg_dir: true
  entry_points:
    - mako-render=mako.cmd:cmdline
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - markupsafe >=0.9.2

  run:
    - python
    - markupsafe >=0.9.2

test:
  imports:
    - mako
    - mako.ext
  commands:
    - mako-render --help

about:
  home: http://www.makotemplates.org/
  license_file: LICENSE
  license: MIT
  summary: A super-fast templating language that borrows the best ideas from the existing templating languages.
  doc_url: http://docs.makotemplates.org/en/latest/
  dev_url: https://bitbucket.org/zzzeek/mako/src

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
