{% set name = "Mako" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e9e345a41924a954251b95b4b28e14a301145b544901332e658907a7464b6b2

build:
  noarch: python
  preserve_egg_dir: true
  entry_points:
    - mako-render=mako.cmd:cmdline
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*
    - pip
    - markupsafe >=0.9.2
  run:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*
    - markupsafe >=0.9.2

test:
  imports:
    - mako
    - mako.ext
  commands:
    - mako-render --help

about:
  home: http://www.makotemplates.org/
  license_file: LICENSE
  license: MIT
  summary: A super-fast templating language that borrows the best ideas from the existing templating languages.
  doc_url: http://docs.makotemplates.org/en/latest/
  dev_url: https://bitbucket.org/zzzeek/mako/src

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
