{% set name = "Mako" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f054a5ff4743492f1aa9ecc47172cb33b42b9d993cffcc146c9de17e717b0307

build:
  noarch: python
  preserve_egg_dir: true
  entry_points:
    - mako-render=mako.cmd:cmdline
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - importlib-metadata
    - markupsafe >=0.9.2
    - pip
  run:
    - python >=3.6
    - importlib-metadata
    - markupsafe >=0.9.2

test:
  imports:
    - mako
    - mako.ext
  commands:
    - mako-render --help

about:
  home: http://www.makotemplates.org/
  license_file: LICENSE
  license: MIT
  summary: A super-fast templating language that borrows the best ideas from the existing templating languages.
  doc_url: http://docs.makotemplates.org/en/latest/
  dev_url: https://github.com/sqlalchemy/mako

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
