travis:
  secure:
    BINSTAR_TOKEN: BMkk8/DvyTr7aj5ObFyC3YUc0r2uOwnHWE4p+AQjX8vc/llOeKzAGO+zqGylhcplgLRotEgGKLlwI24vMnUfKFBcQ1srPEwWSAdlHt0CD3aXN9taSuh7AttJsXZmGpqZ4pmOIGxbUNZk0GD0pqx3qt0HAaEDwF4xHfkOtWCpbnXm308srC9baM4AWwiU8Ir8cBLUPmHh2sUe/VzkbFSwIZCIv0GmeTPFFtIwOcsVnMAEjx6sOHWZgD/TkfMb+LrWaptR9rtdWGiI/jqbGKs9MRAVTCCZSKFpTJ9Sz65eBgCXCB4q8bfn6sV634L8rHijgHcppi3oyh6sKtUQ5MttPXd6CgtwQvkFd9siD1+Jaa1njGQO5Kkr19BOGxjZ7sQx5S43UuRcaNVFY6k2DQqJkD8h8IxI4TcBlfAhw9tsSpo+APY86GoAaVuR7HdKDSf2ec3mSI9za2YLIlNs6lz+oACziD7gROfATukIhC+UDLEvXCoaVADUC63ADSlPFRzHoLIOfTjbzSlE0fpFmznEcHmVngB9TpCIps2bwkdSlu7teP+AOlbcmEc0TjX/K06OKCyzjw2o6uQWd9q/eLm8F+KhxQPsF1QUR6WKgM6Fp7FTMOK0syh9DEJ+aRhX0SK84Tfw+D719YADC/ELNdSz8lP9Az1qlpoZjUvXaYDnE28=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
